---
- name: setup user-directories config
  copy:
    src: files/config/user-dirs.dirs
    dest: /home/luc/.config/user-dirs.dirs
    owner: luc
    group: luc
  register: userdirectories

- name: create user-directories
  file:
    path: '/home/luc/{{ item.src }}'
    state: directory
    mode: '0755'
    owner: luc
    group: luc
  loop:
    - {src: 'active'}
    - {src: 'dwnld'}
    - {src: 'pics'}
    - {src: 'docs'}
    - {src: 'dev'}

- name: delete old user-directories
  file:
    path: '/home/luc/{{ item.src }}'
    state: absent
  loop:
    - {src: 'Desktop'}
    - {src: 'Documents'}
    - {src: 'Downloads'}
    - {src: 'Music'}
    - {src: 'Pictures'}
    - {src: 'Public'}
    - {src: 'online'}
  command: xdg-user-dirs-update
  when: userdirectories.changed

- name: ensure setup dir exists
  file:
    path: /home/luc/.luc/setup
    state: directory
    recurse: yes
    mode: '0755'
    owner: luc
    group: luc

- name: Ensure sshfs is installed
  apt:
    name: sshfs
    state: present

- name: Ensure the ~/online dir exists
  file:
    path: '/home/luc/online'
    state: directory

- name: Mount remote directory
  become_user: luc
  shell: "sshfs -p 2002 luc@lucemans.com:/drv/lion/luc /home/luc/online"
  args:
    chdir: /home/luc
  changed_when: false