---
- hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/vscode-extensions.yml
    - vars/calibrate.yml
  
  roles:
    - base
    - persistence
    - desktop
    - calibrate