---
- hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/vscode-extensions.yml

  tasks:
    - name: install htop
      package:
        name:
          - htop
          - tmux
          - git
          - dconf-cli
          - python3-psutil

    - name: copy wallpaper
      copy:
        src: files/images/eff_bg.jpg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpg

    - name: set wallpaper
      become_user: luc
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"
    
    - name: set wallpaper position
      become_user: luc
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
    
    - name: copy lucrc
      copy:
        src: files/config/lucrc
        dest: /home/luc/.lucrc
        owner: luc
        group: luc
    
    - name: link lucrc
      lineinfile:
        path: /home/luc/.bashrc
        line: source ~/.lucrc
        state: present
        owner: luc
        group: luc

    - name: setup user-directories config
      copy:
        src: files/config/user-dirs.dirs
        dest: /home/luc/.config/user-dirs.dirs
        owner: luc
        group: luc
      register: userdirectories
    
    - name: create user-directories
      file:
        path: '/home/luc/{{ item.src }}'
        state: directory
        mode: '0755'
        owner: luc
        group: luc
      loop:
        - {src: 'active'}
        - {src: 'dwnld'}
        - {src: 'pics'}
        - {src: 'docs'}
        - {src: 'dev'}

    - name: trigger user-directories update
      become_user: luc
      command: xdg-user-dirs-update
      when: userdirectories.changed

    - name: install vscode repo's
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
      register: vscoderepo
    
    - name: update apt repos
      apt:
        update_cache: yes
      when: vscoderepo.changed

    - name: install vscode
      apt:
        name:
          - code

    - name: "fetch installed extensions"
      become_user: luc
      shell: "code --list-extensions"
      register: extensionlist
      changed_when: "'error' in extensionlist.stdout" # So it gives a green checkmark all the time

    - name: "install VS Code extensions"
      become_user: luc
      shell: "code --install-extension {{ item }}"
      when: item not in extensionlist.stdout
      args:
        executable: /bin/bash
      with_items:
        - "{{ visual_studio_code_extensions }}"
      register: vscode_result
      changed_when: "'already installed' not in vscode_result.stdout"