---
- name: Make sure autoswitching is disabled
  ansible.builtin.lineinfile:
    path: /etc/pulse/default.pa
    state: absent
    regexp: 'load-module module-switch-on-port-available'
  become: true