---
- name: Add brave signing key
  apt_key:
    url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
    state: present
- name: install brave repo's
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    state: present
  register: braverepo

- name: update apt repos
  apt:
    update_cache: yes
  when: braverepo.changed

- name: install brave
  apt:
   name: "brave-browser"
   state: present
