---
- name: update apt repos
  apt:
    update_cache: yes
    
- name: install vscode repo's
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  register: vscoderepo

- name: update apt repos
  apt:
    update_cache: yes
  when: vscoderepo.changed

- name: install vscode
  apt:
    name:
      - code

- name: "fetch installed extensions"
  become_user: luc
  shell: "code --list-extensions"
  register: extensionlist
  changed_when: false
  
- name: "install VS Code extensions"
  become_user: luc
  shell: "code --install-extension {{ item }}"
  when: item not in extensionlist.stdout
  with_items:
    - "{{ visual_studio_code_extensions }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"