---
- name: Install flameshot
  apt:
    name: flameshot
    state: present

- name: Remove keybind for normal screenshot key
  become_user: luc
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screenshot"
    value: "'[]'"

- name: Name it keybind for normal screenshot key
  become_user: luc
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'FLAMESHOT (ANSIBLE)'"

# gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot "[]"
# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ name 'flameshot'
# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ command '/snap/bin/flameshot gui'
# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/flameshot/ binding 'Print'

- name: Bind it keybind for normal screenshot key
  become_user: luc
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'/usr/bin/flameshot gui'"
  
- name: Command it keybind for normal screenshot key
  become_user: luc
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'Print'"
  
- name: Create keybind for normal screenshot key
  become_user: luc
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"