---
- name: install htop
  package:
    state: present
    name:
      - apt-transport-https
      - curl
      - gnupg
      - htop
      - tmux
      - git
      - dconf-cli
      - python3-psutil
      - latexmk
      - xclip
      - ripgrep
      - fzf
      # - texlive-full

- name: copy lucrc
  copy:
    src: files/config/lucrc
    dest: /home/luc/.lucrc
    owner: luc
    group: luc

- name: link lucrc
  lineinfile:
    path: /home/luc/.bashrc
    line: source ~/.lucrc
    state: present
    owner: luc
    group: luc