---
- name: install htop
  package:
    state: present
    name:
      - apt-transport-https
      - curl
      - gnupg
      - htop
      - tmux
      - git
      - dconf-cli
      - python3-psutil
- name: copy lucrc
  copy:
    src: files/config/lucrc
    dest: /home/luc/.lucrc
    owner: luc
    group: luc

- name: link lucrc
  lineinfile:
    path: /home/luc/.bashrc
    line: source ~/.lucrc
    state: present
    owner: luc
    group: luc

- name: setup user-directories config
  copy:
    src: files/config/user-dirs.dirs
    dest: /home/luc/.config/user-dirs.dirs
    owner: luc
    group: luc
  register: userdirectories

- name: create user-directories
  file:
    path: '/home/luc/{{ item.src }}'
    state: directory
    mode: '0755'
    owner: luc
    group: luc
  loop:
    - {src: 'active'}
    - {src: 'dwnld'}
    - {src: 'pics'}
    - {src: 'docs'}
    - {src: 'dev'}

- name: trigger user-directories update
  become_user: luc
  command: xdg-user-dirs-update
  when: userdirectories.changed