---
- name: Add Azure Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: install azure repo's
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ stable main
    state: present
  register: azurerepo

- name: update apt repos
  apt:
    update_cache: yes
  when: azurerepo.changed

- name: install azure
  apt:
   name: "azure-cli"
   state: present