---
- name: Import the APT repo key (Debian)
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"

- name: Create the APT repository (Debian)
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ansible_distribution_release}} main"
    filename: azure-cli
    state: present
  register: azurerepo

- name: update apt repos
  apt:
    update_cache: yes
  when: azurerepo.changed

- name: install azure
  apt:
   name: "azure-cli"
   state: present