---
- name: copy wallpaper1
  copy:
    src: files/macos.jpg
    dest: /usr/share/backgrounds/macos.jpeg

- name: copy wallpaper2
  copy:
    src: files/eff_bg.jpg
    dest: /usr/share/backgrounds/eff.jpeg

- name: set wallpaper
  become_user: luc
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/eff.jpeg'"

- name: set wallpaper position
  become_user: luc
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
